import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = (props: any) => {
  // check if wallet is connected
  // if yes, display address / ENS
  // if no, display placeholder "connect wallet"

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { props.account ? props.account.address : props.ta }
    </div>
  )
}

export default Home
